on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          extra-files: pom.xml

  build:
    needs: [release-please]
    runs-on: ubuntu-latest
    env:
      MAJOR: ${{ needs.release-please.outputs.major }}
      MINOR: ${{ needs.release-please.outputs.minor }}
      PATCH: ${{ needs.release-please.outputs.patch }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Set version
        run: mvn versions:set -DnewVersion="${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}"
      
      - run: mvn install -ntp
      - uses: actions/upload-artifact@v3
        with:
          path: target/*.jar
          name: spring-boot-application.jar

  upload-artifact-to-release:
    needs: [build, release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: spring-boot-application.jar
      
      - name: Upload artifact
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: |
            spring-boot-application.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
